### ISSUE TITLE
Handle Networkconnection

### ISSUE THREAD

**Issue by BioPhoton** [ChristopherPHolder/ufo#20]
As some of the application's depend on a network connection we need to handle it's state.

The logic of the Websocke as well as the UI depends on a stable connection. Id the connection drops we have to handle errors and informing the user about it.

**TODOS:**
- [x] Implement a API `/is-online` that returns 1 to get a way to check if a internet connection is given
- [x] Implement a `NetworkConnection` service that exposes the online status
- [x] Implement a `Ws` service that wraps the default RxJS `WebSocketSubject`
  - [x] implement a `init` method to initialize the connecction logic
  - [x] disconnect the ws id the network connection drops
  - [x] disconnect the ws id the network connection drops 
- [x] Disable the `SimpleAuditForm` if the connection dropped
- [x] Enable  the `SimpleAuditForm` if the connection establishes again
- [x] Initialize the WS login after the first interaction that requires a WS connection is done (e.g. click the submit button, open a result)
- [x] Add disabled styles to forms
- [x] Remove old code
